server:
  port: 8080

spring:
  application:
    name: leyue-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能
          lower-case-service-id: true  # 使用小写服务名，默认是大写

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: debug 